### ISSUE TITLE
bugjar fails with TclError: out of stack space error

### ISSUE THREAD

**Issue by unode** [beeware/bugjar#12]
I'm running bugjar with python 2.7.5 on Gentoo Linux.
Bugjar was installed on a virtualenv using pip install bugjar.

The script I'm running contains only a print statement, nothing else.
The script was launched using: `bugjar script.py`

```
Listening on 0.0.0.0:3742 for a bugjar client
Got connection from ('127.0.0.1', 46871)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/unode/.virtualenvs/bugjar/lib/python2.7/site-packages/bugjar/connection.py", line 56, in command_buffer
    getattr(debugger, 'on_%s' % event)(**data)
  File "/home/unode/.virtualenvs/bugjar/lib/python2.7/site-packages/bugjar/connection.py", line 227, in on_stack
    self.view.on_stack(stack=stack)
  File "/home/unode/.virtualenvs/bugjar/lib/python2.7/site-packages/bugjar/view.py", line 469, in on_stack
    self.file_notebook.select(self.stack_frame)
  File "/usr/lib64/python2.7/lib-tk/ttk.py", line 885, in select
    return self.tk.call(self._w, "select", tab_id)
TclError: out of stack space (infinite loop?)
```

After this I also tried to install latest version directly from github but the error persisted.

The GUI is still displayed but it doesn't display any useful information. The code panel is black. The variables panel displays "builtins, globals, locals" but nothing under `Values`.

**Comment by johnzhou721** [comment]
Non-reproducable.

**Comment by unode** [comment]
Sorry this ticket is 12 years old...

**Comment by johnzhou721** [comment]
That's fine... sorry for my terse comment.  #12 is 12 years old -- a nice easter egg :)
