### ISSUE TITLE
can't get bugjar to start.

### ISSUE THREAD

**Issue by oz123** [beeware/bugjar#24]
```
$ bugjar pri.py
Listening on 0.0.0.0:3742 for a bugjar client
Got connection from ('127.0.0.1', 49185)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/site-packages/bugjar/connection.py", line 56, in command_buffer
    getattr(debugger, 'on_%s' % event)(**data)
  File "/usr/lib64/python2.7/site-packages/bugjar/connection.py", line 227, in on_stack
    self.view.on_stack(stack=stack)
  File "/usr/lib64/python2.7/site-packages/bugjar/view.py", line 464, in on_stack
    self.file_notebook.select(self.stack_frame)
  File "/usr/lib64/python2.7/lib-tk/ttk.py", line 888, in select
    return self.tk.call(self._w, "select", tab_id)
TclError: out of stack space (infinite loop?)

```

No clue how to solve this...

**Comment by freakboy3742** [comment]
That's definitely odd. What can you tell me about pri.py? I can only guess that something about that script is confusing bugjar.

As an aside; bugjar is very-early prototype software, not really ready for public consumption.

**Comment by oz123** [comment]
here is `pri.py`:
```
 $ cat pri.py 
print("hello")

a= 1
a = a +2
```

**Comment by freakboy3742** [comment]
This is likely a Python 2 compatibility issue, so it should be safe to close.
