### ISSUE TITLE
ModuleNotFoundError: No module named 'Tkinter'

### ISSUE THREAD

**Issue by Code4SAFrankie** [beeware/bugjar#29]
Running `bugjar mypythonfile.py` gives this error:

```
Traceback (most recent call last):
  File "e:\wpy-3710\python-3.7.1.amd64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\wpy-3710\python-3.7.1.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\WPy-3710\python-3.7.1.amd64\Scripts\bugjar.exe\__main__.py", line 5, in <module>
  File "e:\wpy-3710\python-3.7.1.amd64\lib\site-packages\bugjar\main.py", line 4, in <module>
    from Tkinter import *
ModuleNotFoundError: No module named 'Tkinter'
```

Python version: 3.7.1
Using Conda? PipEnv? PyEnv? Pex? pip on WinPython
OS version: Windows 10 version 1903
Browser version: Firefox 69.0

**Comment by freakboy3742** [comment]
You opened this bug on the repository for the BeeWare website, but this looks like it's a report with [Bugjar](https://github.com/beeware/bugjar); I've transferred it.

Since you're on Windows, I'm going to guess that you're hitting the same problem that is addressed by [this note](https://cricket.readthedocs.io/en/v0.2.3/#problems-under-windows) in the Cricket documentation. We're in the process of replacing Tkinter specifically because of these sort of problems.
